// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var jsonString = haxe_Resource.getString("data.json");
	Main.data = JSON.parse(jsonString);
	Main.filtered = Main.data.slice();
	Main.injectCSS();
	Main.buildFilterPanel();
	Main.buildTable();
};
Main.injectCSS = function() {
	var css = "\r\n            table {\r\n                border-collapse: collapse;\r\n                margin: 20px;\r\n                font-family: Arial, sans-serif;\r\n                width: 600px;\r\n            }\r\n            th, td {\r\n                padding: 10px;\r\n                border: 1px solid #ccc;\r\n                text-align: left;\r\n            }\r\n            th {\r\n                background: #444;\r\n                color: white;\r\n                cursor: pointer;\r\n                user-select: none;\r\n            }\r\n            tr:nth-child(even) {\r\n                background: #f2f2f2;\r\n            }\r\n            tr:hover {\r\n                background: #e0e0e0;\r\n            }\r\n            #searchBox {\r\n                margin: 20px;\r\n                padding: 8px;\r\n                width: 300px;\r\n                font-size: 16px;\r\n            }\r\n            .sort-icon {\r\n                margin-left: 6px;\r\n                font-size: 12px;\r\n                opacity: 0.7;\r\n            }\r\n        ";
	var style = window.document.createElement("style");
	style.textContent = css;
	window.document.head.appendChild(style);
};
Main.buildFilterPanel = function() {
	var doc = window.document;
	var container = doc.createElement("div");
	container.id = "filterPanel";
	container.style.margin = "20px";
	container.style.display = "flex";
	container.style.flexWrap = "wrap";
	container.style.gap = "10px";
	var nameInput = doc.createElement("input");
	nameInput.placeholder = "Filter by name";
	nameInput.oninput = function(_) {
		Main.applyFilters();
	};
	nameInput.id = "filterName";
	container.appendChild(nameInput);
	var cityInput = doc.createElement("input");
	cityInput.placeholder = "Filter by city";
	cityInput.oninput = function(_) {
		Main.applyFilters();
	};
	cityInput.id = "filterCity";
	container.appendChild(cityInput);
	var ageMin = doc.createElement("input");
	ageMin.placeholder = "Min age";
	ageMin.type = "number";
	ageMin.oninput = function(_) {
		Main.applyFilters();
	};
	ageMin.id = "filterAgeMin";
	container.appendChild(ageMin);
	var ageMax = doc.createElement("input");
	ageMax.placeholder = "Max age";
	ageMax.type = "number";
	ageMax.oninput = function(_) {
		Main.applyFilters();
	};
	ageMax.id = "filterAgeMax";
	container.appendChild(ageMax);
	var scoreMin = doc.createElement("input");
	scoreMin.placeholder = "Min score";
	scoreMin.type = "number";
	scoreMin.oninput = function(_) {
		Main.applyFilters();
	};
	scoreMin.id = "filterScoreMin";
	container.appendChild(scoreMin);
	doc.body.appendChild(container);
};
Main.applyFilters = function() {
	var doc = window.document;
	var name = doc.getElementById("filterName").value.toLowerCase();
	var city = doc.getElementById("filterCity").value.toLowerCase();
	var ageMinStr = doc.getElementById("filterAgeMin").value;
	var ageMaxStr = doc.getElementById("filterAgeMax").value;
	var scoreMinStr = doc.getElementById("filterScoreMin").value;
	var ageMin = ageMinStr == "" ? null : Std.parseInt(ageMinStr);
	var ageMax = ageMaxStr == "" ? null : Std.parseInt(ageMaxStr);
	var scoreMin = scoreMinStr == "" ? null : Std.parseInt(scoreMinStr);
	var _g = [];
	var _g1 = 0;
	var _g2 = Main.data;
	while(_g1 < _g2.length) {
		var v = _g2[_g1];
		++_g1;
		if(name != "" && v.name.toLowerCase().indexOf(name) == -1 ? false : city != "" && v.city.toLowerCase().indexOf(city) == -1 ? false : ageMin != null && v.age < ageMin ? false : ageMax != null && v.age > ageMax ? false : scoreMin != null && v.score < scoreMin ? false : true) {
			_g.push(v);
		}
	}
	Main.filtered = _g;
	Main.buildTable();
};
Main.buildTable = function() {
	var doc = window.document;
	var old = doc.getElementById("peopleTable");
	if(old != null) {
		old.remove();
	}
	var table = doc.createElement("table");
	table.id = "peopleTable";
	var header = doc.createElement("tr");
	Main.addHeader(header,"Name","name");
	Main.addHeader(header,"Age","age");
	Main.addHeader(header,"City","city");
	Main.addHeader(header,"Score","score");
	table.appendChild(header);
	var _g = 0;
	var _g1 = Main.filtered;
	while(_g < _g1.length) {
		var person = _g1[_g];
		++_g;
		var row = doc.createElement("tr");
		row.appendChild(Main.cell(person.name));
		row.appendChild(Main.cell(person.age == null ? "null" : "" + person.age));
		row.appendChild(Main.cell(person.city));
		row.appendChild(Main.cell(person.score == null ? "null" : "" + person.score));
		table.appendChild(row);
	}
	doc.body.appendChild(table);
};
Main.cell = function(text) {
	var td = window.document.createElement("td");
	td.textContent = text;
	return td;
};
Main.addHeader = function(row,title,field) {
	var th = window.document.createElement("th");
	var label = window.document.createElement("span");
	label.textContent = title;
	var icon = window.document.createElement("span");
	icon.className = "sort-icon";
	if(Main.currentSortColumn == field) {
		icon.textContent = Main.sortAscending ? "▲" : "▼";
	}
	th.appendChild(label);
	th.appendChild(icon);
	th.onclick = function(_) {
		if(Main.currentSortColumn == field) {
			Main.sortAscending = !Main.sortAscending;
		} else {
			Main.currentSortColumn = field;
			Main.sortAscending = true;
		}
		Main.filtered.sort(function(a,b) {
			var va = Reflect.field(a,field);
			var vb = Reflect.field(b,field);
			if(va < vb) {
				if(Main.sortAscending) {
					return -1;
				} else {
					return 1;
				}
			}
			if(va > vb) {
				if(Main.sortAscending) {
					return 1;
				} else {
					return -1;
				}
			}
			return 0;
		});
		Main.buildTable();
	};
	row.appendChild(th);
};
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( _g ) {
		return null;
	}
};
var Std = function() { };
Std.__name__ = true;
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Resource = function() { };
haxe_Resource.__name__ = true;
haxe_Resource.getString = function(name) {
	var _g = 0;
	var _g1 = haxe_Resource.content;
	while(_g < _g1.length) {
		var x = _g1[_g];
		++_g;
		if(x.name == name) {
			if(x.str != null) {
				return x.str;
			}
			var b = haxe_crypto_Base64.decode(x.data);
			return b.toString();
		}
	}
	return null;
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
haxe_io_Bytes.__name__ = true;
haxe_io_Bytes.ofString = function(s,encoding) {
	if(encoding == haxe_io_Encoding.RawNative) {
		var buf = new Uint8Array(s.length << 1);
		var _g = 0;
		var _g1 = s.length;
		while(_g < _g1) {
			var i = _g++;
			var c = s.charCodeAt(i);
			buf[i << 1] = c & 255;
			buf[i << 1 | 1] = c >> 8;
		}
		return new haxe_io_Bytes(buf.buffer);
	}
	var a = [];
	var i = 0;
	while(i < s.length) {
		var c = s.charCodeAt(i++);
		if(55296 <= c && c <= 56319) {
			c = c - 55232 << 10 | s.charCodeAt(i++) & 1023;
		}
		if(c <= 127) {
			a.push(c);
		} else if(c <= 2047) {
			a.push(192 | c >> 6);
			a.push(128 | c & 63);
		} else if(c <= 65535) {
			a.push(224 | c >> 12);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		} else {
			a.push(240 | c >> 18);
			a.push(128 | c >> 12 & 63);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		}
	}
	return new haxe_io_Bytes(new Uint8Array(a).buffer);
};
haxe_io_Bytes.prototype = {
	getString: function(pos,len,encoding) {
		if(pos < 0 || len < 0 || pos + len > this.length) {
			throw haxe_Exception.thrown(haxe_io_Error.OutsideBounds);
		}
		if(encoding == null) {
			encoding = haxe_io_Encoding.UTF8;
		}
		var s = "";
		var b = this.b;
		var i = pos;
		var max = pos + len;
		switch(encoding._hx_index) {
		case 0:
			var debug = pos > 0;
			while(i < max) {
				var c = b[i++];
				if(c < 128) {
					if(c == 0) {
						break;
					}
					s += String.fromCodePoint(c);
				} else if(c < 224) {
					var code = (c & 63) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code);
				} else if(c < 240) {
					var c2 = b[i++];
					var code1 = (c & 31) << 12 | (c2 & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code1);
				} else {
					var c21 = b[i++];
					var c3 = b[i++];
					var u = (c & 15) << 18 | (c21 & 127) << 12 | (c3 & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(u);
				}
			}
			break;
		case 1:
			while(i < max) {
				var c = b[i++] | b[i++] << 8;
				s += String.fromCodePoint(c);
			}
			break;
		}
		return s;
	}
	,toString: function() {
		return this.getString(0,this.length);
	}
};
var haxe_io_Encoding = $hxEnums["haxe.io.Encoding"] = { __ename__:true,__constructs__:null
	,UTF8: {_hx_name:"UTF8",_hx_index:0,__enum__:"haxe.io.Encoding",toString:$estr}
	,RawNative: {_hx_name:"RawNative",_hx_index:1,__enum__:"haxe.io.Encoding",toString:$estr}
};
haxe_io_Encoding.__constructs__ = [haxe_io_Encoding.UTF8,haxe_io_Encoding.RawNative];
var haxe_crypto_Base64 = function() { };
haxe_crypto_Base64.__name__ = true;
haxe_crypto_Base64.decode = function(str,complement) {
	if(complement == null) {
		complement = true;
	}
	if(complement) {
		while(HxOverrides.cca(str,str.length - 1) == 61) str = HxOverrides.substr(str,0,-1);
	}
	return new haxe_crypto_BaseCode(haxe_crypto_Base64.BYTES).decodeBytes(haxe_io_Bytes.ofString(str));
};
var haxe_crypto_BaseCode = function(base) {
	var len = base.length;
	var nbits = 1;
	while(len > 1 << nbits) ++nbits;
	if(nbits > 8 || len != 1 << nbits) {
		throw haxe_Exception.thrown("BaseCode : base length must be a power of two.");
	}
	this.base = base;
	this.nbits = nbits;
};
haxe_crypto_BaseCode.__name__ = true;
haxe_crypto_BaseCode.prototype = {
	initTable: function() {
		var tbl = [];
		var _g = 0;
		while(_g < 256) {
			var i = _g++;
			tbl[i] = -1;
		}
		var _g = 0;
		var _g1 = this.base.length;
		while(_g < _g1) {
			var i = _g++;
			tbl[this.base.b[i]] = i;
		}
		this.tbl = tbl;
	}
	,decodeBytes: function(b) {
		var nbits = this.nbits;
		var base = this.base;
		if(this.tbl == null) {
			this.initTable();
		}
		var tbl = this.tbl;
		var size = b.length * nbits >> 3;
		var out = new haxe_io_Bytes(new ArrayBuffer(size));
		var buf = 0;
		var curbits = 0;
		var pin = 0;
		var pout = 0;
		while(pout < size) {
			while(curbits < 8) {
				curbits += nbits;
				buf <<= nbits;
				var i = tbl[b.b[pin++]];
				if(i == -1) {
					throw haxe_Exception.thrown("BaseCode : invalid encoded char");
				}
				buf |= i;
			}
			curbits -= 8;
			out.b[pout++] = buf >> curbits & 255;
		}
		return out;
	}
};
var haxe_io_Error = $hxEnums["haxe.io.Error"] = { __ename__:true,__constructs__:null
	,Blocked: {_hx_name:"Blocked",_hx_index:0,__enum__:"haxe.io.Error",toString:$estr}
	,Overflow: {_hx_name:"Overflow",_hx_index:1,__enum__:"haxe.io.Error",toString:$estr}
	,OutsideBounds: {_hx_name:"OutsideBounds",_hx_index:2,__enum__:"haxe.io.Error",toString:$estr}
	,Custom: ($_=function(e) { return {_hx_index:3,e:e,__enum__:"haxe.io.Error",toString:$estr}; },$_._hx_name="Custom",$_.__params__ = ["e"],$_)
};
haxe_io_Error.__constructs__ = [haxe_io_Error.Blocked,haxe_io_Error.Overflow,haxe_io_Error.OutsideBounds,haxe_io_Error.Custom];
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
haxe_Resource.content = [{ name : "data.json", data : "Ww0KICB7ICJuYW1lIjogIkFsaWNlIiwgImFnZSI6IDMzLCAiY2l0eSI6ICJMb25kb24iLCAic2NvcmUiOiA4OCB9LA0KICB7ICJuYW1lIjogIkJvYiIsICAgImFnZSI6IDI1LCAiY2l0eSI6ICJQYXJpcyIsICAic2NvcmUiOiA5MiB9LA0KICB7ICJuYW1lIjogIlN1c2FuIiwgImFnZSI6IDM0LCAiY2l0eSI6ICJHcmltc2J5IiwgInNjb3JlIjogOTAgfSwNCiAgeyAibmFtZSI6ICJKb2huIiwgICAiYWdlIjogMjYsICJjaXR5IjogIlN3YW5zZWEiLCAgInNjb3JlIjogODkgfQ0KXQ"}];
js_Boot.__toStr = ({ }).toString;
Main.currentSortColumn = "";
Main.sortAscending = true;
haxe_crypto_Base64.CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
haxe_crypto_Base64.BYTES = haxe_io_Bytes.ofString(haxe_crypto_Base64.CHARS);
Main.main();
})({});
